name: iOS Build

on:
  push:
    branches:
      - main

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.13.0  # Update based on your project needs

      - name: Install Dependencies
        run: flutter pub get

      - name: Enable iOS
        run: flutter config --enable-ios

      - name: Build iOS
        run: flutter build ios --no-codesign

      - name: Check if build directory exists
        run: ls -la build/ios/iphoneos/ || echo "Build directory not found"

      - name: Upload Build Artifact
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: ios-build
          path: build/ios/iphoneos/
